// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for CategoryType.
const (
	Income    CategoryType = "income"
	Investing CategoryType = "investing"
	Outgoing  CategoryType = "outgoing"
)

// Category defines model for category.
type Category struct {
	CategoryId   int          `json:"category_id"`
	CategoryName string       `json:"category_name"`
	CategoryType CategoryType `json:"category_type"`
}

// CategoryType defines model for category_type.
type CategoryType string

// CategoryYearSummary defines model for category_year_summary.
type CategoryYearSummary struct {
	CategoryId   int          `json:"category_id"`
	CategoryName string       `json:"category_name"`
	CategoryType CategoryType `json:"category_type"`
	Count        int          `json:"count"`
	Price        []int        `json:"price"`
	Total        int          `json:"total"`
}

// Record defines model for record.
type Record struct {
	CategoryId   int       `json:"category_id"`
	CategoryName string    `json:"category_name"`
	Datetime     time.Time `json:"datetime"`
	From         string    `json:"from"`
	Id           int       `json:"id"`
	Memo         string    `json:"memo"`
	Price        int       `json:"price"`
	Type         string    `json:"type"`
}

// RecordCount defines model for record_count.
type RecordCount struct {
	Num *int `json:"num,omitempty"`
}

// ReqRecord defines model for req_record.
type ReqRecord struct {
	CategoryId int     `json:"category_id"`
	Datetime   *string `json:"datetime,omitempty"`
	From       *string `json:"from,omitempty"`
	Memo       *string `json:"memo,omitempty"`
	Price      int     `json:"price"`
	Type       *string `json:"type,omitempty"`
}

// GetV3RecordParams defines parameters for GetV3Record.
type GetV3RecordParams struct {
	// Num the number of records
	Num        *int    `form:"num,omitempty" json:"num,omitempty"`
	Offset     *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Yyyymm     *string `form:"yyyymm,omitempty" json:"yyyymm,omitempty"`
	CategoryId *int    `form:"category_id,omitempty" json:"category_id,omitempty"`
}

// PostV3RecordJSONRequestBody defines body for PostV3Record for application/json ContentType.
type PostV3RecordJSONRequestBody = ReqRecord
