name: Backend CI

on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.3"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Build binary
        run: make bin

      - name: Verify binary exists
        run: |
          if [ ! -f ./bin/mawinter ]; then
            echo "Binary not found!"
            exit 1
          fi
          echo "Binary successfully built"
          ls -lh ./bin/mawinter
